### PR TITLE
Gnome46

### PR DESCRIPTION
**Pull request by Isopolito**

### CODE REVIEW

**Comment by szpak** [comment]
Thanks @Isopolito for backporting your work. It will be helpful also for me.

**Comment by Isopolito** [comment]
You're welcome @szpak, I was actually going to submit a forked version of this extension to gnome extensions under my account so that people could use it again. 

I'd rather not have to maintain it though if somebody already is 😄. Are you or someone else going to integrate the latest changes and submit a new version to gnome extensions?

**Comment by szpak** [comment]
Unfortunately, I'm just an early adopter of this extension. Only @vancha has an ability to handle that, but (s)he seems to be busy with the other things recently. So, unless (s)he comes back to handle the update, I think that forking the project is the right way to go, to make it more popular though the extension portal.

**Comment by Isopolito** [comment]
Gotcha, I'll probably do that then so other people can use it again. I haven't seen any activity in here for years

**Comment by Isopolito** [comment]
@szpak fyi: https://github.com/vancha/gnomeShellBinaryClock/issues/15

**Comment by vancha** [comment]
Wow I would like to deeply apologise for not actually seeing github's miniscule notification dot. Thanks for the contribution! I would not have expected people to have the patience to wade through code of such quality as the one in this project.  Some maintainer I am o.o

**Comment by Isopolito** [comment]
Hi @vancha, no worries life gets in the way. Because of the lack of activity over the years I forked it to keep the binary clock alive: https://extensions.gnome.org/extension/6901/gbinaryclock/

So no pressure to update things here if you have other priorities.

Cheers and thanks for building this.

**Comment by vancha** [comment]
@Isopolito I'm just sorry I ignored something I figured no one would actually use. But i love that you uploaded it and made it available again ^^ Should I ask for deletion of my version of the extension from gnome extensions? that way the same thing won't show up twice.

**Comment by Isopolito** [comment]
@vancha it's all good, it actually happened to me once. I accidentally had git hub notifications getting directed to spam and didn't respond to ppl for about 6 months  :)

As for deleting your extension--it's your call since you're the original creator of this.

I'd be happy to run with it from here on out. I maintain another extension so I'm already having to make the periodic updates from gnome's breaking changes to the extension apis.

**Comment by vancha** [comment]
Hmm well as you could probably tell from the code, I don't actually know any gjs, nor do i know anything about building a gnome extension. All i guess i can do is rely on others to fix things if they break. If you wouldn't mind taking over, that would probably be best for future users of the extension :)

**Comment by Isopolito** [comment]
Don't feel bad, I don't think many people truly know gjs ;). It can be a bit obfuscated. Either way the code you wrote for the binary clock is legit--works great and looks great.

I'll take it from here, and thanks again for building it.

**Comment by szpak** [comment]
> Should I ask for deletion of my version of the extension from gnome extensions?

I believe it is not needed. You might just add a link to a forked version in the description noting that Gnome 45+ is supported there (or maybe even add "deprecated" in the plugin name).

**Comment by vancha** [comment]
> > Should I ask for deletion of my version of the extension from gnome extensions?
> 
> I believe it is not needed. You might just add a link to a forked version in the description noting that Gnome 45+ is supported there (or maybe even add "deprecated" in the plugin name).

Done and done :)

**Pull request closed without merging**
